config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'messages/index'
  get 'messages/create'
  get 'conversations/index'
  get 'conversations/create'
  get 'users/show'
  get 'dashboards/index'
  devise_for :users

  # Pages
  root to: 'pages#home'
  get 'feed', to: 'pages#feed'
  get 'dashboard', to: 'dashboards#index'
  get 'account', to: 'accounts#index'

  resources :users, only: [:show, :index]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :recipient_id

  scope :involving, -> (user) {
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  }

  scope :between, -> (user_A, user_B) {
    where("(conversations.sender_id = ? OR conversations.recipient_id = ?) OR conversations.sender_id = ? OR conversations.recipient_id = ?", user_A, user_B, user_B, user_A)
  }

end

app/models/hospital.rb
class Hospital < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates_presence_of :content, :conversation_id, :user_id
  # after_create_commit :create_notification

  def message_time
    self.created_at.strftime("%v")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    feed_path # your path
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = Conversation.involving(current_user)
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
   before_action :authenticate_user!
   before_action :set_conversation

   def index
     if current_user == @conversation.sender || current_user == @conversation.recipient
      @other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
      @messages = @conversation.messages.order("created_at DESC")
     else
      redirect_to conversations_path, alert: "You don't have permissions to view this."
     end
   end

   def create
     @message = @conversation.messages.new(message_params)
     @messages = @conversation.messages.order("created_at DESC")
     if @message.save
      redirect_to conversation_messages_path(@conversation)
     end
   end

   private

   def set_conversation
     @conversation = Conversation.find(params[:conversation_id])
   end

   def message_params
     params.require(:message).permit(:content, :user_id)
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @user = current_user
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
  def feed
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show, :destroy]

  def show
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_for(user)
    "https://res.cloudinary.com/djpmfj4ym/image/upload/v1610833661/default_user_avatar_iplrkg.png"
  end

  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end
end

app/views/accounts/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center p-3">
    <div class="col-xs-12 w-100">
      <div class="d-flex justify-content-between">
        <h3><strong>Dashboard<span style="color: #E67E22">.</span></strong></h3>
        <%= link_to @user do %>
          <i class="fas fa-pen"></i>
        <% end %>
      </div>
      <br>
      <div class="wall-card text-center">
        <%= image_tag avatar_for(@user), class: 'avatar' %>
        <h3 class="mt-3"><%= @user.first_name %> <i class="fas fa-user-check orange ml-2"></i></h3>
        <p class="mt-3"><%= @user.email %></p>
      </div>
      <br>

      <p>General</p>
      <div class="container">
          <div class="card-grid">

            <div class="card-setting myBox">
              <%= link_to root_path do %>
                <div class="d-flex flex-row align-items-center">
                  <%= svg "icon-dashboard" %>
                  <div class="ml-4">
                    <p class="blue"><strong>Candidate Settings</strong><br>
                    Manage your payroll, rates and availability</p>
                  </div>
                  <i class="fas fa-chevron-right"></i>
                </div>
              <% end %>
            </div>

            <div class="card-setting myBox">
              <%= link_to root_path do %>
                <div class="d-flex flex-row align-items-center justify-content-between">
                  <%= svg "icon-notification" %>
                  <div class="ml-4">
                    <p class="blue"><strong>Notifications</strong><br>
                    Change your notification settings</p>
                  </div>
                  <i class="fas fa-chevron-right"></i>
                </div>
              <% end %>
            </div>

            <div class="card-setting myBox">
              <%= link_to root_path do %>
                <div class="d-flex flex-row align-items-center justify-content-between justify-content-between">
                  <%= svg "icon-notification" %>
                  <div class="ml-4">
                    <p class="blue"><strong>Privacy</strong><br>
                    Update your password</p>
                  </div>
                  <i class="fas fa-chevron-right"></i>
                </div>
              <% end %>
            </div>

            <div class="card-setting myBox">
              <%= link_to root_path do %>
                <div class="d-flex flex-row align-items-center">
                  <%= svg "icon-notification" %>
                  <div class="ml-4">
                    <p class="blue"><strong>Referrals</strong><br>
                    Invite your friends, earn money</p>
                    <span class="badge badge-pill badge-primary">Coming soon</span>
                  </div>
                  <i class="fas fa-chevron-right"></i>
                </div>
              <% end %>
            </div>

          </div>
      </div>
      <br>

      <div class="container">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-ghost" %>
      </div>


      <br>
      <br>
      <br>

    </div>
  </div>
</div>

<script>
  $(".myBox").click(function() {
  window.location = $(this).find("a").attr("href");
  return false;
});
</script>

app/views/conversations/_conversations.html.erb
<% @conversations.each do |conversation| %>
    <% @other = current_user == conversation.sender ? conversation.recipient : conversation.sender %>
    <%= link_to conversation_messages_path(conversation) do %>

        <div class="message-data">
          <%= image_tag avatar_for(@other), class: "avatar" %>
          <div class="message-data-body">
            <div class="message-data-header">
              <span class="message-data-name ml-3 mr-3">From <%= @other.first_name + " " + @other.last_name.first %></span>
              <span class="message-data-time"><%= conversation.messages.last.message_time %></span>
            </div>
            <div class="message-data-content my-message">
              <%= conversation.messages.last.content %>
            </div>
          </div>
          <br/>
          <div class="conversation-actions">
            <%= link_to conversation_messages_path(conversation) do %>
              Read <i class="fas fa-pencil-alt"></i>
            <% end %>
          </div>
        </div>
        <br>

    <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="container content">
  <div class="row d-flex justify-content-center p-3">
    <div class="col-xs-12 w-100">

      <h3><strong>Inbox<span style="color: #E67E22">.</span></strong></h3>
      <br>

      <div class="container">
        <% if @conversations.exists? %>
          <% @conversations.each do |conversation| %>
            <% other = current_user == conversation.sender ? conversation.recipient : conversation.sender %>

                    <div class="conversation myBox">
                      <%= image_tag avatar_for(other), class: "avatar" %>
                      <div class="conversation-body">
                        <div class="conversation-header">
                          <span class="conversation-name ml-3">From <%= other.first_name %></span>
                          <span class="conversation-time ml-3"><%= conversation.messages.last.message_time %></span>
                        </div>
                        <div class="conversation-content">
                          <p><%= conversation.messages.last.content %></p>
                        </div>
                      </div>
                      <div class="conversation-actions">
                        <%= link_to conversation_messages_path(conversation) do %>
                          Read <i class="fas fa-pencil-alt"></i>
                        <% end %>
                        <a href="#">Delete <i class="far fa-trash-alt"></i></a>
                      </div>
                    </div>

          <% end %>
          <% else %>
          <div class="wall-card">
            <p>You have no conversations.</p>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<script>
  $(".myBox").click(function() {
  window.location = $(this).find("a").attr("href");
  return false;
});
</script>

app/views/dashboards/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center p-3">
    <div class="col-xs-12 w-100">

      <br>
      <nav>
        <div class="nav nav-pills nav-fill pill-orange" id="nav-tab" role="tablist">
          <a class="nav-item nav-link orange active" id="nav-account-tab" data-toggle="tab" href="#nav-account" role="tab" aria-controls="nav-account" aria-selected="true">Account</a>
          <a class="nav-item nav-link orange" id="nav-Jobs-tab" data-toggle="tab" href="#nav-Jobs" role="tab" aria-controls="nav-Jobs" aria-selected="false">Jobs</a>
          <a class="nav-item nav-link orange" id="nav-past-tab" data-toggle="tab" href="#nav-past" role="tab" aria-controls="nav-past" aria-selected="false">News</a>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-account" role="tabpanel" aria-labelledby="nav-account-tab">
          <br>

          <!-- Account status -->
          <div class="wall-card">
            <!-- Balance -->
            <div class="d-flex justify-content-between">
              <p>Account balance</p>
              <p class="blue"><strong>£1,240.36</strong></p>
            </div>
            <!-- Account actions -->
            <div class="list-actions">
              <a href="/" class="badge badge-pill badge-light">Get paid</a>
              <a href="/" class="badge badge-pill badge-light">Add money</a>
            </div>
            <br>
            <!-- Transactions -->
            <div class="d-flex justify-content-between">
              <h3>Transactions</h3>
              <a href="/">See all</a>
            </div>
            <div class="transaction-show">
              <div><i class="fas fa-hospital green"></i></div>
              <div class="transaction-content">
                <p class="blue"><strong>London NHS Trust</strong></p>
                <p><small>14th January</small></p>
              </div>
              <div class="transaction-amount">
                <p class="green">+£250</p>
              </div>
            </div>

            <div class="transaction-show">
              <div><i class="fas fa-wallet"></i></div>
              <div class="transaction-content">
                <p class="blue"><strong>Withdraw</strong></p>
                <p><small>12th January</small></p>
              </div>
              <div class="transaction-amount">
                <p class="red">+£250</p>
              </div>
            </div>

          </div>
          <br>
          <!-- Suggestions -->
          <p>Suggested for you</p>
          <br>
          <div class="card-line">
            <div class="small-card" style="background-color: #B31423">
              <p>x</p>
              <p>Refer friends and earn £5</p>
            </div>
          </div>


        </div>

        <div class="tab-pane fade" id="nav-past" role="tabpanel" aria-labelledby="nav-past-tab">
          <br>
        </div>

        <div class="tab-pane fade" id="nav-Jobs" role="tabpanel" aria-labelledby="nav-Jobs-tab">
          <br>
          <!-- Job card -->
          <div class="wall-card">
            <h3 class="blue">Swansea Hospital</h3>
            <h4>ICU Nurse band 5</h4>
            <h1>£25/Hour</h1>
            <hr class="blue">
            <p><strong>Location:</strong> Swansea bay, Wales</p>
            <p><strong>Duration:</strong>12 Hours</p>
            <div class="mt-4">
              <%= link_to "Apply", root_path, class: "btn btn-blue" %>
              <%= link_to "More info", root_path, class: "btn btn-ghost" %>
            </div>
          </div>

        </div>

      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hyppkrates | Healthcare employee app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<% if message.user == current_user %>
  <div class="message-data">
    <%= image_tag avatar_for(message.user), class: "avatar" %>
    <div class="message-data-body">
      <div class="message-data-header">
        <span class="message-data-name ml-3 mr-3"><%= message.user.first_name%></span>
        <span class="message-data-time"><%= message.message_time %></span>
      </div>
      <div class="message-data-content my-message">
        <%= message.content %>
      </div>
    </div>
    <br/>
  </div>
  <br>
<% else %>
  <div class="message-data">
    <div class="message-data-body">
      <div class="message-data-header justify-content-end">
        <span class="message-data-time mr-3"><%= message.message_time %></span>
        <span class="message-data-name mr-3"><%= message.user.first_name%></span>
      </div>
      <div class="message-data-content other-message">
        <%= message.content %>
      </div>
    </div>
    <%= image_tag avatar_for(message.user), class: "avatar" %>
    <br/>
  </div>
  <br>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<div class="container content">
  <div class="row d-flex justify-content-center p-3">
    <div class="col-xs-12 col-md-9 w-100">
      <div class="message-input">
        <nav aria-label="breadcrumb">
          <ol class="list-inline">
            <li class="list-inline-item"><h4><%= link_to 'Inbox', conversations_path %></h4></li>
            <li class="list-inline-item">/</li>
            <li class="list-inline-item active" aria-current="page">Message with <%= @other.first_name %></li>
          </ol>
        </nav>
        <div class="message-input-header">
          <span>

            <input id="conversation_id" type="hidden" value="<%= @conversation.id %>">
          </span>

        </div>
        <br>
        <div class="card-body">
          <div class="container">
            <%= form_for [@conversation, @conversation.messages.new] do |f| %>
              <div class="form-group">
                <%= f.text_field :content, placeholder: "Add a message", class: "form-control" %>
              </div>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <div>
                <br>
                <%= f.submit "Send Message", class: "btn-signup" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <br>
    <hr>
    <div>
      <h3>Conversation with <strong><%= link_to @other.first_name, @other %></strong></h3>
    </div>
    <br>

      <div id="chat">
        <%= render @messages %>
      </div>


    </div>
  </div>
</div>

app/views/pages/feed.html.erb
<div class="container">
  <div class="row d-flex justify-content-center p-3">
    <div class="col-xs-12 w-100">

      <br>
      <nav>
        <div class="nav nav-pills nav-fill pill-orange" id="nav-tab" role="tablist">
          <a class="nav-item nav-link orange active" id="nav-account-tab" data-toggle="tab" href="#nav-account" role="tab" aria-controls="nav-account" aria-selected="true">Account</a>
          <a class="nav-item nav-link orange" id="nav-Jobs-tab" data-toggle="tab" href="#nav-Jobs" role="tab" aria-controls="nav-Jobs" aria-selected="false">Jobs</a>
          <a class="nav-item nav-link orange" id="nav-past-tab" data-toggle="tab" href="#nav-past" role="tab" aria-controls="nav-past" aria-selected="false">News</a>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-account" role="tabpanel" aria-labelledby="nav-account-tab">
          <br>

          <!-- Account status -->
          <div class="wall-card">
            <!-- Balance -->
            <div class="d-flex justify-content-between">
              <p>Account balance</p>
              <p class="blue"><strong>£1,240.36</strong></p>
            </div>
            <!-- Account actions -->
            <div class="list-actions">
              <a href="/" class="badge badge-pill badge-light">Get paid</a>
              <a href="/" class="badge badge-pill badge-light">Add money</a>
            </div>
            <br>
            <!-- Transactions -->
            <div class="d-flex justify-content-between">
              <h3>Transactions</h3>
              <a href="/">See all</a>
            </div>
            <div class="transaction-show">
              <div><i class="fas fa-hospital green"></i></div>
              <div class="transaction-content">
                <p class="blue"><strong>London NHS Trust</strong></p>
                <p><small>14th January</small></p>
              </div>
              <div class="transaction-amount">
                <p class="green">+£250</p>
              </div>
            </div>

            <div class="transaction-show">
              <div><i class="fas fa-wallet"></i></div>
              <div class="transaction-content">
                <p class="blue"><strong>Withdraw</strong></p>
                <p><small>12th January</small></p>
              </div>
              <div class="transaction-amount">
                <p class="red">+£250</p>
              </div>
            </div>

          </div>
          <br>
          <!-- Suggestions -->
          <p>Suggested for you</p>
          <br>
          <div class="card-line">
            <div class="small-card" style="background-color: #B31423">
              <p>x</p>
              <p>Refer friends and earn £5</p>
            </div>
          </div>


        </div>

        <div class="tab-pane fade" id="nav-past" role="tabpanel" aria-labelledby="nav-past-tab">
          <br>
        </div>

        <div class="tab-pane fade" id="nav-Jobs" role="tabpanel" aria-labelledby="nav-Jobs-tab">
          <br>
          <!-- Job card -->
          <div class="wall-card">
            <h3 class="blue">Swansea Hospital</h3>
            <h4>ICU Nurse band 5</h4>
            <h1>£25/Hour</h1>
            <hr class="blue">
            <p><strong>Location:</strong> Swansea bay, Wales</p>
            <p><strong>Duration:</strong>12 Hours</p>
            <div class="mt-4">
              <%= link_to "Apply", root_path, class: "btn btn-blue" %>
              <%= link_to "More info", root_path, class: "btn btn-ghost" %>
            </div>
          </div>

        </div>

      </div>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hero-banner-bg">
  <div class="hero-banner">
    <div class="row">
      <div class="col-12 col-md-6">
        <h1>
          The all-in-one healthcare candidate platform
        </h1>
        <p>
          Operate, manage your income, get financial and heatlth support with Hyppkrates all-in-one health candidate app.
          Hold still while we get your back.
        </p>
        <div class="mt-4">
          <%= link_to "Get Started", new_user_registration_path, class: "btn btn-blue" %>
          <%= link_to "Get Contacted", root_path, class: "btn btn-ghost-white" %>
        </div>
      </div>
      <div class="col-12 col-md-6">
        insert image / video
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container footer-container">
    <div class="row footer-brand">
      Hyppkrtes<span style="color: #8D010E">.</span>
    </div>
  </div>

  <div class="footer-container">
    <div class="row">
      <div class="col-sm-12 col-md-3">
        <div class="mb-3">
          <h4>Candidates</h4>
          <ul class="footer-links">
            <li><%= link_to "Features", feed_path %></li>
            <li><a href="/host">Community</a></li>
            <li><a href="">Candidate terms</a></li>
            <li><a href="/faqs">FAQ</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-12 col-md-3">
        <div class="mb-3">
          <h4>Company</h4>
          <ul class="footer-links">
            <li><a href="">Our mission</a></li>
            <li><a href="">About us</a></li>
            <li><a href="">Career</a></li>
            <li><a href="">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="mb-3">
          <h4><strong>The first app for medical employees</strong></h4>
          <p class="footer-text">Discover our unique eco-system build by Medical people for medical people. Payroll, jobs, shifts, mental support, news and exclusive perks specificialy designed for Healthcare employees. </p>
        </div>
      </div>
    </div>
    <hr>
  </div>

  <div class="footer-container">
    <div class="row align-items-center legal-links">
      <div class="col-md-4 col-sm-6 col-xs-12 footer-links">
        <a class="legal-text mr-3" href="/terms">Terms</a>
        <a class="legal-text mr-3" href="/terms/privacy">Privacy</a>
        <a class="legal-text" href="/terms/cookies">Cookies</a>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12 legal-links footer-links">
          &copy; 2021 - Enferm Ltd. All rights reserved
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="footer-links links-socialmedia">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-youtube"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-github"></i></a>
        </div>
      </div>

    </div>
  </div>
  <br>
  <br>
</footer>

app/views/shared/_navbar.html.erb
<!-- DESKTOP NAVBAR -->
<nav class="desktop">
  <div class="navbar navbar-expand-sm navbar-light navbar-enferm">
    <a class="navbar-brand" href="/">
      Hyppkrtes<span style="color: #8D010E">.</span>
    </a>

    <div class="form-inline">
      <% if user_signed_in? %>
        <%= link_to conversations_path(current_user) do %>
          <i class="fas fa-envelope inactive-gray"></i>
        <% end %>
        <%= link_to feed_path do %>
          <i class="fas fa-bell ml-3 inactive-gray"></i>
        <% end %>
      <% end %>

      <ul class="navbar-nav mr-auto desktop">
        <li class="nav-item mx-2">
        </li>
        <% if !user_signed_in? %>
            <li class="nav-item mx-2">
              <%= link_to "Login", new_user_session_path, class: "btn btn-ghost" %>
            </li>
        <% else %>
          <li class="dropdown bl-orange">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_for(current_user), class: "avatar" %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <li class="nav-item">
                <li><%= link_to "Saved", feed_path, class: "dropdown-item" %></li>
              </li>
              <li class="nav-item">
                <li><%= link_to "Shifts", feed_path, class: "dropdown-item" %></li>
              </li>
              <li class="nav-item">
                <li><%= link_to "Inbox", feed_path, class: "dropdown-item" %></li>
              </li>

              <li class="dropdown-divider"></li>

              <li><%= link_to "My Account", account_path, class: "dropdown-item" %></li>

              <li class="dropdown-divider"></li>
              <% if current_user.admin == true %>
                <li><%= link_to "Admin dashboard", admin_root_path, class: "dropdown-item" %>
                </li>
              <% end %>
              <li><%= link_to "Help & FAQ", feed_path, class: "dropdown-item" %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

<!-- MOBIL TOP NAVBAR -->

<nav class="mobile">
  <div class="form-inline d-flex justify-content-between pl-3 pr-3">
    <% if user_signed_in? %>
      <div class="mt-3">
        <%= link_to dashboard_path do %>
          <%= image_tag avatar_for(@user), class: 'avatar' %>
        <% end %>
      </div>
      <div>
        <%= link_to conversations_path(current_user) do %>
          <i class="fas fa-envelope inactive-gray"></i>
        <% end %>
        <%= link_to feed_path do %>
          <i class="fas fa-bell ml-3 inactive-gray"></i>
        <% end %>
      </div>
    <% end %>

  </div>
</nav>



<!-- MOBILE BOTTOM NAVBAR -->

<nav>
  <!-- Links -->
  <div class="mobile-btm-navbar">
    <a href="<%= feed_path %>" class="btm-nav-btn <%= current_page?(feed_path) ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-home'%>Home</a>
    <% if !user_signed_in? %>
      <a href="<%= new_user_registration_path %>" class="btm-nav-btn <%= current_page?(new_user_registration_path) ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-signup'%>Sign up</a>
      <a href="<%= new_user_session_path %>" class="btm-nav-btn <%= current_page?(new_user_session_path) ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-user'%>Login</a>
    <% else %>
      <a href="<%= dashboard_path %>" class="btm-nav-btn <%= root_path ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-bank'%>Dashboard</a>
      <a href="<%= root_path %>" class="btm-nav-btn <%= root_path ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-trips'%>Calendar</a>
      <a href="<%= root_path %>" class="btm-nav-btn <%= root_path ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-saved'%>Jobs</a>
      <a href="<%= root_path %>" class="btm-nav-btn <%= root_path ? "active-blue" : "inactive-gray" %>"><%= svg 'icon-app'%>Perks</a>
    <% end %>
  </div>
</nav>